name: build_deploye_full_pipeline
run-name: Build_Deploy. Branch="${{github.ref_name}}",Env = "${{inputs.environment}}".

on:
  workflow_dispatch:
    inputs:
      envirnoment:
        type: environment
        description: select the environment
      SONAR_FLAG:
        type: boolean
        description: Sonar Scan True or false
      FORTIFY_FLAG:
        type: boolean
        description: Fortify Scan True or false

jobs:
  Build-job-non-prod:
    if: inputs.environment !='prod'
    uses: git-dillip/common-workflow-repo/.github/workflows/build-deploye-api.yml@dev-env
    with:
      ENV_NAME: ${{inputs.environment}}
    secrets: inherit

  Build-job-prod:
    if: inputs.environment =='prod'
    uses: git-dillip/common-workflow-repo/.github/workflows/build-deploye-api.yml@main
    with:
      ENV_NAME: ${{inputs.environment}}
    secrets: inherit

  Sonar_scan:
    if: inputs.SONAR_FLAG == true
    uses: git-dillip/common-workflow-repo/.github/workflows/sonar-api.yml@main
    with:
      ENV_NAME: ${{inputs.environment}}
    secrets: inherit

  Fortify:
    if: inputs.FORTIFY_FLAG ==true
    uses: git-dillip/common-workflow-repo/.github/workflows/fortify.yml@main
    with:
      ENV_NAME: ${{inputs.environment}}
    secrets: inherit

